spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vectordb
    username: postgres
    password: "DevAhn##2026"
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: never

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.devahn.backend.domain

server:
   port: 8080